<?php

namespace AMAPBundle\Repository;

/**
 * AmapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmapRepository extends \Doctrine\ORM\EntityRepository
{
    function getAmap($id){
        return $this->getEntityManager()->createQueryBuilder('a')->select('a')->where('a.id = ?1')->from('AMAPBundle:Amap','a')->setParameter(1,$id);
    } 
}
