<?php

namespace AMAPBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    function getAmap($amap){
        return $this->getEntityManager()->createQueryBuilder('p')->select('p')->where('p.amap = ?1')->from('AMAPBundle:Panier','p')->setParameter(1,$amap);
    } 
}
