<?php

namespace AMAPBundle\Repository;

/**
 * TypeActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActeurRepository extends \Doctrine\ORM\EntityRepository
{
}
