amap_homepage:
    path:     /
    defaults: { _controller: AMAPBundle:Default:index }

amap_produit:
    path:     /produit
    defaults: { _controller: AMAPBundle:Produit:index }
    
amap_produit_ajouter:
    path:     /produit/ajouter
    defaults: { _controller: AMAPBundle:Produit:ajouter }
    
amap_panier:
    path:     /panier
    defaults: { _controller: AMAPBundle:Panier:ajouter }
    
amap_panier_ajouter:
    path:     /panier/ajouter
    defaults: { _controller: AMAPBundle:Panier:ajouterMessage }
    
amap_stock_ajouter:
    path:     /produit/stock/ajouter
    defaults: { _controller: AMAPBundle:Produit:ajouterStockMessage }    
    
amap_acteur:
    path:     /acteur
    defaults: { _controller: AMAPBundle:Acteur:ajouter }
    
amap_contrat:
    path:     /contrat
    defaults: { _controller: AMAPBundle:Contrat:creer }
    
amap_adresse:
    path: /adresse
    defaults: { _controller: AMAPBundle:Acteur:ajouterAdresse }
    