amap_homepage:
    path:     /
    defaults: { _controller: AMAPBundle:Default:index }
    
amap_admin:
    path:     /admin
    defaults: { _controller: AMAPBundle:Admin:index }
    
amap_creer_panier:
    path:     /admin/creerPanier
    defaults: { _controller: AMAPBundle:Admin:creerPanier }
    
amap_ajout_prod_panier:
    path:     /admin/ajoutProdPanier
    defaults: { _controller: AMAPBundle:Admin:ajouterProduitPanier }
    
amap_retrait_panier:
    path:     /admin/retraitPanier
    defaults: { _controller: AMAPBundle:Admin:retraitPanier }
    
amap_lister_produit_admin:
    path:     /admin/listerProduit
    defaults: { _controller: AMAPBundle:Admin:listerProduit }
    
amap_select_amap:
    path:     /selectAmap
    defaults: { _controller: AMAPBundle:Default:selectAmap }

amap_produit:
    path:     /produit
    defaults: { _controller: AMAPBundle:Produit:index }

amap_produit_ajouter:
    path:     /produit/ajouter
    defaults: { _controller: AMAPBundle:Produit:ajouter }

amap_panier:
    path:     /panier
    defaults: { _controller: AMAPBundle:Panier:ajouter }

amap_consulter_panier:
    path:     /consulterPaniers
    defaults: { _controller: AMAPBundle:Panier:consulter }

amap_panier_ajouter:
    path:     /panier/ajouter
    defaults: { _controller: AMAPBundle:Panier:ajouterMessage }

amap_entrepot:
    path:     /entrepot
    defaults: { _controller: AMAPBundle:Entrepot:creer }

amap_stock:
    path:     /stock
    defaults: { _controller: AMAPBundle:Stock:index }

amap_stock_ajouter:
    path:     /produit/stock/ajouter
    defaults: { _controller: AMAPBundle:Stock:ajouterStockMessage }

amap_acteur:
    path:     /acteur
    defaults: { _controller: AMAPBundle:Acteur:ajouter }

amap_contrat:
    path:     /contrat
    defaults: { _controller: AMAPBundle:Contrat:creer }

amap_livraison:
    path:     /livraison
    defaults: { _controller: AMAPBundle:Livraison:index }

amap_effectue_livraison:
    path:     /livraison/{id}
    defaults: { _controller: AMAPBundle:Livraison:effectuer }

amap_amap:
    path:     /amap
    defaults: { _controller: AMAPBundle:Amap:ajouter }
    
amap_effectuer_one_livraison:
    path:     /livraison/{idpanier}/one/{id}/{date}
    defaults: { _controller: AMAPBundle:Livraison:effectuerOne }